lgallard/terraform-aws-backup

README.md
iam.tf
main.tf
outputs.tf
selection.tf
variables.tf

I just needed a possibility to switch AWS Backups on/off. Feel free to incorporate this code.

enabled flag

---

CHANGELOG.md
main.tf

Fix space in completion_window value

---

CHANGELOG.md
README.md
outputs.tf

* Allows attaching an already created IAM role to the plan
* Fix plane IAM role output

Allows attaching an already created IAM role to the plan

---

CHANGELOG.md
README.md
examples/complete_plan/README.md
examples/complete_plan/main.tf
examples/selection_by_tags/README.md
examples/selection_by_tags/main.tf
examples/simple_plan/README.md
examples/simple_plan/main.tf
examples/simple_plan_using_variables/README.md
examples/simple_plan_using_variables/main.tf
selection.tf
variables.tf

Add support for several selection tags

---

CHANGELOG.md
README.md
examples/complete_plan/README.md
examples/complete_plan/main.tf
examples/complete_plan/provider.tf
examples/simple_plan/README.md
examples/simple_plan/main.tf
examples/simple_plan/provider.tf
examples/simple_plan_using_variables/README.md
examples/simple_plan_using_variables/main.tf
examples/simple_plan_using_variables/provider.tf
main.tf
variables.tf

Add support for enable_continuous_backup

---

CHANGELOG.md
README.md

Fix selection-tags in README

---

CHANGELOG.md
main.tf

* Change formatting TF code 
* Update CHANGELOG

Release 0.12.1

---

CHANGELOG.md
README.md
examples/selection_by_tags/README.md
examples/selection_by_tags/main.tf

ENHANCEMENTS:
* Update examples and READMEs

Update examples and READMEs

---

CHANGELOG.md
README.md
versions.tf

ENHANCEMENTS:
* Change required provider block definition

Change required provider block definition

---

.terraform.lock.hcl
README.md
iam.tf

This is to support AWS Backup S3 capabilities https://aws.amazon.com/blogs/aws/preview-aws-backup-adds-support-for-amazon-s3/

feat: Allow S3 backup

---

iam.tf

Hi @lgallard,
Thanks for your work!
We need this module in a different AWS partition, so I suggest the following change.
Let me know your thoughts.
Thanks.

Added support for any AWS partitions

---

README.md
versions.tf

to update aws provider constrain
close https://github.com/lgallard/terraform-aws-backup/issues/62

fix(version): fix aws provider constrain

---

.pre-commit-config.yaml
README.md
iam.tf
selection.tf
variables.tf

* allow to set iam role name if u use labels with specific naming otherwise use predefined
* prettier iam policy documents
* up pre-commits versions

chore: iam role name, pretty iam policy document, precommit updates

---

main.tf
variables.tf
versions.tf

Add force-destroy flag to backup vault https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_vault#force_destroy

Add force-destroy flag to backup vault

---

README.md
examples/simple_plan_using_lock_configuration/README.md
examples/simple_plan_using_lock_configuration/main.tf
examples/simple_plan_using_lock_configuration/provider.tf
examples/simple_plan_using_lock_configuration/terraform.tfvars
examples/simple_plan_using_lock_configuration/variables.tf
main.tf
variables.tf

A vault lock helps protect backups from lifecycle changes, accidental deletion, or malicious activities.
Closes #71

Add new resource aws_backup_vault_lock_configuration

---

iam.tf
main.tf
notifications.tf

Fix dependencies between resources

---

CHANGELOG.md
README.md

* Add https://github.com/lgallard/terraform-aws-backup/pull/75
* Update README and CHANGELOG

Release 0.19.1

---

CHANGELOG.md

FIXES:
* Fix inconsistent plan role output (thanks @miachm)

Release 0.19.2 - Fix inconsistent plan role output

---

CHANGELOG.md
README.md
iam.tf

ENHANCEMENTS:
* Add tags to `aws_iam_policy` resources
Fixes #79

feature: Add aws_iam_policy tags

---

CHANGELOG.md
README.md

ENHANCEMENTS:
* Add conditional for `aws_backup_plan` to avoid creation if no rules are provided (thanks @gpdenny)

Release 0.20.0

---

examples/simple_plan_with_report/README.md
examples/simple_plan_with_report/main.tf
examples/simple_plan_with_report/provider.tf
examples/simple_plan_with_report/terraform.tfvars
examples/simple_plan_with_report/variables.tf
reports.tf
variables.tf

Me again :wave:  
Add feature for creating backup reports, also added an example with the required S3 Bucket Policy.

feat: add backup report feature

---

CHANGELOG.md
README.md
examples/simple_plan_with_report/main.tf

ENHANCEMENTS:
* Add backup report feature (thanks @gpdenny)

Release 0.21.0 - Add backup report feature

---

CHANGELOG.md

ENHANCEMENTS:
* Add input variable to opt-out of SNS policy (thanks @henriknj)

Release input variable to opt-out of SNS policy

---

.gitignore
.terraform-docs.yml
README.md

- Add .terraform-docs.yml configuration file for documentation generation
- Update .gitignore to exclude .terraform-docs.yml
- Modify README.md to include documentation generation markers
---
This pull request includes significant updates to the Terraform AWS Backup module documentation and examples. The changes enhance the module's usability by providing detailed usage examples and improving the overall documentation structure.
* [`.terraform-docs.yml`](diffhunk://#diff-1870602938553c78bf18176e356ff2e25b50db7bdae4b6421f0b1b6bdd5a026dR1-R121): Added a configuration file to generate Terraform documentation in markdown format, including detailed sections on features, usage, and known issues.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1): …

chore: Add .terraform-docs.yml configuration and update .gitignore

---

CHANGELOG.md
README.md

This pull request includes an update to the `CHANGELOG.md` file to document the changes in version 0.23.2. The update notes that a missing README file has been added.
* [`CHANGELOG.md`](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR5-R10): Added a new section for version 0.23.2, documenting the addition of the missing README file.

feat: Add missing README file

---

selection.tf

See: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection#selecting-backups-by-conditions
Fixes: #93

fix `conditions` to re-allow flexible use of them

---

.gitignore

- Added .terraformrc and terraform.rc to ignore CLI configuration files.
- Included all files in the .cursor/rules directory to be ignored.

chore: Update .gitignore to include additional files

---

.github/workflows/claude-code-review.yml

- Add GitHub Actions workflow for AI-powered code reviews
- Supports multiple review modes (hunt, analyze, security, performance, review)
- Comment-triggered reviews using `codebot [mode]` commands
- Manual workflow dispatch via GitHub CLI
- **Comment Triggers**: Use `codebot hunt`, `codebot security`, etc. in PR comments
- **Multiple Modes**: hunt (quick bug detection), analyze (deep analysis), security, performance, comprehensive review
- **Manual Execution**: Run via `gh workflow run claude-code-review.yml -f review_mode=security`
- **Sticky Comments**: Better UX with persistent review comments

feat: add claude code review workflow

---

.github/workflows/feature-discovery.yml

The feature discovery workflow fails at the Environment Diagnostics step due to trying to validate a non-existent npm package:
Unknown command: "error"
To see a list of supported npm commands, run:
npm help
**Inconsistency in workflow configuration:**
- ✅ MCP Config correctly uses Docker image: `hashicorp/terraform-mcp-server`
- ❌ Diagnostics step incorrectly tries to validate npm package: `@modelcontextprotocol/server-terraform`
The npm package doesn't exist, causing a 404 error that blocks the entire workflow.
**Replace npm package validation with Docker image check:**
**Before:**
Package lookup failed
**After:**
docker.io/hashicorp/terraform-mcp-server:latest
🚀 **Unblocks automated GitHub issue creation**
This fix allows the workflow to:
1. ✅ Pass diagnostics without npm 404 errors
2. …

fix: Replace non-existent npm package validation with Docker image check
