- main.tf
Under **Inputs**, `vault_name` is marked as **not required**.
However, failing to provide this variable causes the module to complain about a missing `target_vault_name` -- _which is not listed under **Inputs**_ -- and throws this error:
> Error: Missing required argument
> 
>   with module.rds_backup.aws_backup_plan.ab_plan[0],
>   on .terraform/modules/rds_backup/main.tf line 10, in resource "aws_backup_plan" "ab_plan":
>   10: resource "aws_backup_plan" "ab_plan" {
> 
> The argument "rule.1.target_vault_name" is required, but no definition was found.
This PR should modify this behavior so that, it first looks up the value of `target_vault_name`, then `vault_name`, and finally returns `Default` in case neither is set.
> Fixed error when missing optional vault_name

- selection.tf
fix https://github.com/lgallard/terraform-aws-backup/issues/48
> fix backup selection re-creation

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- examples/complete_plan/provider.tf
- examples/simple_plan/provider.tf
- examples/simple_plan_using_variables/provider.tf
- versions.tf
As reported in #58, there were some incompatibilities issues among Terraform versions and the AWS provider for Terraform version `0.12.x.`
After checking, the lower Terraform version that downloads a AWS provider higher than `3.72.0 `is Terraform version `0.12.31`. 
It closes #58
> Fix terraform version constraints

- outputs.tf
The output "plan_role" was sometimes an ARN and sometimes a name (depending of the var inputs). 
I think it should return the same type in both cases
> Fix incosistent output

- main.tf
- variables.tf
Thanks for the module :pray:
I'd like to be able to use the same module when creating a standalone vault with no rules to be referenced in a cross-region copy action of another plan.
- Updates `aws_backup_plan` resource count to prevent creation if no plan rules are specified.
> feat: only create aws_backup_plan if rules are provided

- README.md
This pull request includes a small change to the `README.md` file. The change updates the image URL from an AWS Backup image to a Terraform image.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R1): Updated the image URL to use a Terraform image instead of an AWS Backup image.
> fix: Update README icon

- main.tf
- variables.tf
This pull request includes changes to the Terraform configuration for AWS Backup vaults, specifically focusing on improving the validation and configuration logic. The most important changes include the removal of the lifecycle precondition from the `aws_backup_vault` resource and the addition of validation logic to the `locked` variable.
Validation and configuration improvements:
* [`main.tf`](diffhunk://#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbL9-R18): Removed the lifecycle precondition block from the `aws_backup_vault` resource and adjusted the `count` condition in the `aws_backup_vault_lock_configuration` resource to include the `enabled` variable.
* [`variables.tf`](diffhunk://#diff-05b5a57c136b6ff596500bcbfdcff145ef6cddea2a0e86d184d9daa9a65a288eR45-R49): …
> fix: retention days validations

- .github/.release-please-config.json
- Remove "v" prefix from tags and release titles
- Format GitHub release titles with package name and version
> chore: customize release-please configuration

- main.tf
This PR fixes issue #109 where an error occurs when `recovery_point_tags` is not set in the rules block. The error was caused by attempting to use the `length()` function on a potentially null value, which Terraform doesn't allow even when wrapped in `try()`.
- Replace `length(try(rule.value.recovery_point_tags, {})) == 0 ? var.tags : rule.value.recovery_point_tags` with `coalesce(rule.value.recovery_point_tags, var.tags)`
- This change maintains the same functionality but handles null values properly using Terraform's built-in `coalesce` function
Thanks @Edward-Ireson
> fix: simplify recovery point tags assignment

- .github/.release-please-config.json
This pull request includes a small but important change to the `.github/.release-please-config.json` file. The change adds a new configuration option to specify the format of the release tags.
Configuration changes:
* [`.github/.release-please-config.json`](diffhunk://#diff-654b5d1c6182210bb04674196ce31e01a13238f90a807f1a53c2e977687234c1R10-R17): Added the `tag-format` configuration option to specify the format of the release tags.
> chore: update release-please to include tag format versioning

- .github/.release-please-config.json
This pull request includes a change to the `.github/.release-please-config.json` file to update the release title pattern.
* [`.github/.release-please-config.json`](diffhunk://#diff-654b5d1c6182210bb04674196ce31e01a13238f90a807f1a53c2e977687234c1L18): Removed the `release-title-pattern` configuration to streamline the release process.
> chore: Remove release title pattern from release-please configuration

- README.md
- selection.tf
Fixes the "Cannot use a null value in for_each" error reported in issue #174.
- Replace `try()` with `coalesce(try(..., null), {})` pattern for all condition dynamic blocks
- Applied to all three backup selection resources:
- `aws_backup_selection.ab_selection`
- `aws_backup_selection.ab_selections`  
- `aws_backup_selection.plan_selections`
- Affects 12 for_each statements total (4 per resource)
The issue occurred when `condition.value["string_equals"]` (and similar keys) evaluated to null, causing Terraform's for_each to fail. The fix uses `coalesce()` to convert null values to empty maps `{}`, which for_each can handle properly.
- ✅ Terraform validate: Success
- ✅ Pre-commit hooks: Core validation passed  
- ✅ Example configurations: Valid
- ✅ No breaking changes
This change uses the …
> fix: Handle null values in dynamic for_each blocks in selection.tf

- CLAUDE.md
- Add CLAUDE.md with Terraform-specific development guidelines for the terraform-aws-backup module
- Focus on practical patterns: favor `for_each` over `count`, comprehensive testing requirements, and release automation
- Provides module-specific guidance without being overly restrictive
- Created `CLAUDE.md` with development guidelines covering:
- Resource creation patterns (favor `for_each`)
- Testing requirements for new features and modifications
- Release management using release-please
- Module-specific patterns for AWS Backup
- Security considerations and validation practices
> docs: Add project-specific Terraform development guidelines

- .github/workflows/pre-commit.yml
- CLAUDE.md
Add comprehensive pre-commit GitHub Actions workflow for automated code quality validation and formatting.
- Add pre-commit.yml workflow with Terraform formatting, validation, and linting
- Include terraform-docs for automatic documentation generation
- Add TFLint for advanced Terraform analysis and best practices
- Implement intelligent caching for improved performance
- Add comprehensive documentation section to CLAUDE.md
**Automated Code Quality:**
- 🔧 Terraform formatting (`terraform fmt`)
- ✅ Terraform validation (`terraform validate`)  
- 📚 Documentation generation (`terraform-docs`)
- 🔍 TFLint analysis for best practices
- 🧹 File formatting (trailing whitespace, end-of-file fixes)
- 📋 YAML validation
**Performance Optimizations:**
- Smart caching of terraform-docs and tflint …
> feat: add pre-commit workflow for automated code quality

- test_formatting.tf
This PR is created to verify that the pre-commit workflow is working correctly by introducing intentional formatting issues.
The pre-commit workflow should:
1. ❌ **Fail initially** due to formatting issues in `test_formatting.tf`
2. 🔧 **Detect and report** the following issues:
- Extra trailing whitespace
- Missing final newline
- Inconsistent indentation  
- Improper spacing around operators
- Missing spaces after braces
The test file `test_formatting.tf` contains intentional formatting violations to validate that:
- The `trailing-whitespace` hook catches extra spaces
- The `end-of-file-fixer` hook detects missing final newlines
- The `terraform_fmt` hook identifies Terraform formatting issues
- The workflow properly reports incremental file checking on PRs
✅ Pre-commit workflow triggers …
> test: verify pre-commit workflow with formatting issues

- .github/workflows/claude-code-review.yml
- .github/workflows/claude.yml
- Updated `claude-code-review.yml` with comprehensive improvements from terraform-aws-ecr
- Updated `claude.yml` with latest configuration and MCP server integration  
- Enhanced git state management and diff detection strategies
- Added robust error handling and retry logic
- Improved workflow summary and troubleshooting information
- Added commit SHA verification and cache invalidation
- ✅ Synced claude-code-review.yml with latest version (766 lines vs previous 518)
- ✅ Enhanced codebot functionality with better error handling
- ✅ Improved diff detection with multiple fallback strategies
- ✅ Added comprehensive workflow summaries
- ✅ Updated claude.yml with MCP server configuration
- All changes committed successfully
- Workflow structure validated
- Enhanced codebot capabilities ready …
> chore: sync Claude workflows with latest version

- CLAUDE.md
- Optimized CLAUDE.md from 1,281 lines to 405 lines (68% reduction)
- Enhanced with MCP (Model Context Protocol) server integration for real-time validation
- Maintained all essential development guidelines while removing redundancy
- **Removed redundant example configurations**: Replaced 286 lines of inline examples with a concise table referencing the existing `examples/` directory
- **Consolidated security patterns**: Merged 4 similar validation examples into 1 comprehensive pattern
- **Streamlined pre-commit section**: Reduced from 163 to ~30 lines, keeping only essentials
- **Optimized testing section**: Removed inline code, referenced actual test files
- **Condensed development patterns**: Combined similar patterns, removed boilerplate
- **MCP-Powered Validation Workflow**: …
> docs: optimize CLAUDE.md for improved readability and MCP integration

- .github/workflows/feature-discovery.yml
Fixes the AWS Backup Feature Discovery workflow failure by adding the required `id-token: write` permission for OIDC authentication.
The workflow was failing at the "Run Claude Code Feature Discovery" step with the error:
```
Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
Did you remember to add id-token: write to your workflow permissions?
```
Added `id-token: write` to the permissions section of the workflow file `.github/workflows/feature-discovery.yml`.
- ✅ Added `id-token: write` permission to workflow
- ✅ Pre-commit checks passed
- ✅ No breaking changes
Closes #224
> fix: add id-token write permission for OIDC authentication

- .github/workflows/feature-discovery.yml
Completes the workflow fixes for the Claude Code action on master branch that were missing from the previous merge.
The previous PR merge didn't include all the necessary fixes, causing the workflow to fail on master with the same original errors:
- "Tag mode cannot handle workflow_dispatch events"
- GitHub authentication issues
Applied all 4 required fixes to the workflow:
1. **OIDC Permissions**: `id-token: write` (already present)
2. **GitHub Token Environment**: `GITHUB_TOKEN: ${{ secrets.TERRAFORM_AUTOMATION_TOKEN }}`  
3. **Agent Mode**: `mode: agent` parameter for workflow_dispatch support
4. **GitHub Token Parameter**: `github_token: ${{ secrets.TERRAFORM_AUTOMATION_TOKEN }}`
```yaml
env:
CLAUDE_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
+ GITHUB_TOKEN: ${{ …
```
> fix: complete workflow fixes for Claude Code action on master

- .github/workflows/feature-discovery.yml
Fixes MCP server connectivity issues by switching from `TERRAFORM_AUTOMATION_TOKEN` to `CLAUDE_ISSUE_TOKEN`.
The feature discovery workflow was failing because the Terraform MCP server couldn't connect:
```json
{
"name": "terraform", 
"status": "failed"
}
```
This prevented the workflow from:
- Fetching AWS provider documentation
- Discovering new Backup features  
- Creating auto-discovered issues
Changed token configuration to match the **working** ECR repository setup:
```yaml
env:
- GITHUB_TOKEN: ${{ secrets.TERRAFORM_AUTOMATION_TOKEN }}
+ GITHUB_TOKEN: ${{ secrets.CLAUDE_ISSUE_TOKEN }}
with:
- github_token: ${{ secrets.TERRAFORM_AUTOMATION_TOKEN }}
+ github_token: ${{ secrets.CLAUDE_ISSUE_TOKEN }}
```
The ECR repository uses `CLAUDE_ISSUE_TOKEN` and successfully:
- ✅ Connects both …
> fix: replace TERRAFORM_AUTOMATION_TOKEN with CLAUDE_ISSUE_TOKEN for MCP connectivity

- .github/feature-tracker/backup-features.json
- .github/workflows/feature-discovery.yml
Final fix for GitHub issue #224 - resolves git push permissions error in the AWS Backup Feature Discovery workflow.
- Updated workflow permissions from `contents: read` to `contents: write`
- This allows the feature discovery workflow to commit and push tracker updates
- Workflow validated successfully on branch `fix/workflow-git-permissions`
- Complete end-to-end execution confirmed working
- MCP servers connecting properly with HashiCorp Docker server
- Closes #224
> fix: resolve git permissions for feature discovery workflow

- .github/workflows/feature-discovery.yml
Fixes the AWS Backup Feature Discovery workflow to actually create GitHub issues when new features are discovered.
The workflow was successfully discovering AWS Backup features (found 7 new features) but not creating GitHub issues for them. Features were marked as `"status": "pending_creation"` instead of being tracked as actual issues.
1. **Enhanced Claude Code Prompt**: Added explicit instructions for issue creation with detailed templates
2. **Post-Processing Step**: Added backup mechanism to create issues for any features marked as "pending_creation" 
3. **Workflow Summary**: Enhanced reporting to show issue creation status
4. **Issue Templates**: Standardized issue format with auto-discovery metadata
- Updated Claude Code direct_prompt with explicit GitHub issue creation commands
- …
> fix: implement GitHub issue creation for AWS Backup feature discovery

- .github/workflows/feature-discovery.yml
Current workflow creates PRs on every run, even when no new features are discovered. This leads to:
- PR spam from metadata-only updates
- Unnecessary maintenance overhead  
- Git history noise from frequent scan metadata commits
Implement smart PR creation logic that only creates PRs for meaningful changes.
**Smart PR Logic:**
- Only create PRs when `ISSUES_CREATED > 0` (new features discovered)
- Skip PR creation for metadata-only updates
- Preserve scan logs in workflow output instead of creating noise commits
**Enhanced Logging:**
- Clear messaging when PR creation is skipped
- Informative workflow summary showing tracker update status
- Distinguish between "no changes" vs "metadata only" scenarios
**Logic Flow:**
```bash
if [ "$ISSUES_CREATED" -eq 0 ]; then
echo "📊 Tracker updated …
```
> feat: implement smart PR creation for feature tracker updates
